apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
        - name: wordbook-migrate
          image: wordbook-backend:1.0
          imagePullPolicy: IfNotPresent
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 5